name: "Style Lint"

on:
  push:
    branches: ["master"]
    paths: ["_sass/**/*.scss"]
  pull_request:
    paths: ["_sass/**/*.scss"]

jobs:
  stylelint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: latest
      - run: npm i
      - run: npm test
